web/src/ui/components/BuildCard/BuildCard.scss

Fix(front): Fit build card contents onto small screen

---

web/src/ui/pages/Home/Home.js

fix: No race condition on landing default param push

---

web/src/ui/components/BuildCard/ArtifactCard.js
web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/BuildCard/BuildCard.scss

fix: Pull ID in title
fix: Commit sha is a link now
fix: Commit icon hover displays full commit hash
fix: Hover time-from shows full date
fix: Hover time duration details
Related to #71 (fixes some issues; not all)
Closes #82

Fix(front): Improve some API and UI response mapping

---

web/src/ui/components/Header/Header.js
web/src/ui/components/ThemeToggler.js
web/src/ui/pages/Home/Home.js

Fix(front): Hide filters and buttons from unauthorized users

---

web/src/ui/components/BuildList.js

Feat(front): Add UI message when no results found

---

README.md

See root README.md **Philosophy**.

Docs: Small philosophy statement in README

---

web/src/api/dataTransforms.js
web/src/constants/index.js
web/src/store/ResultStore.js
web/src/ui/components/BuildCard/ArtifactCard.js
web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/BuildCard/BuildCard.scss
web/src/ui/components/BuildList.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/pages/Home/Home.js

- Add file size and artifact local path details
- Remove collapse card condition for this merge
Relates to #71

Feat(web): Small additions and fixes

---

web/src/assets/_variables.scss
web/src/ui/components/BuildCard/ArtifactCard.js
web/src/ui/components/BuildCard/BuildCard.js

* Add Build driver to card details
* Add MR driver
* Add artifact driver
* (unrelated: Add github colors to sass variables)
Related to #71

Feat(web): Add build, artifact, and MR driver names to build cards

---

web/src/constants/index.js
web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/BuildCard/BuildCard.scss
web/src/ui/styleTools/buttonStyler.js

* 'Passed' build state tag is a link to build logs.
* Add in more constants from backend to harmonize UI state with API
Related to #71

Feat(web): Style and add links to tags in build cards

---

web/src/store/ResultStore.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/FilterModal/FilterModal.scss
web/src/ui/components/Filters/Filters.js
web/src/ui/components/Filters/Filters.scss
web/src/ui/components/Header/Header.js
web/src/ui/components/ThemeToggler.js

- Remove berty maxi from filters
- Make filter modal scrollable
- Move theme toggler out of header
- Add logout to settings modal
- Style refresh and logout buttons for header
Closes #153

Feat(web): Move logout and theme toggler to filters modal

---

web/src/ui/components/BuildCard/ArtifactCard.js
web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/BuildCard/BuildCard.scss
web/src/ui/styleTools/buttonStyler.js
web/src/util/date.js

Normalize artifact states for artifact button styling
Remove [missing] placeholder text
Add date utility functions
Remove custom button class and show build metadata
Relates to #71

Feat(web): Add some build metadata regardless has_mergerequest

---

web/src/assets/_breakpointMixins.scss
web/src/assets/_variables.scss
web/src/ui/components/BuildCard/ArtifactCard.js
web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/BuildCard/BuildCard.scss

- Fix branchname overflow on small screens
- Add xs screen size
- Make buildcards (not modals or header) friendly for xs screens
Related to #141 
Closes #177

Fix(front): Fix various tag alignment issues for small screens

---

web/src/store/ResultStore.js
web/src/ui/components/Filters/Filters.js
web/src/ui/pages/Home/Home.js

Fix(front): Manual refresh preserves URL bar query

---

go.mod
go.sum
go/cmd/yolo/main.go

feat: HTTP client caching

---

web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/BuildCard/BuildCard.scss

* tidy some getters and remove empty link on commit shas with no commit_url
* remove pointer cursor on readonly buttons

refactor(front): small cleanups in buildCard

---

web/src/assets/main.scss
web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/BuildCard/BuildCard.scss
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/FilterModal/FilterModal.scss
web/src/ui/components/Filters/Filters.scss
web/src/ui/components/Header/Header.scss
web/src/ui/components/ShowFiltersButton.js
web/src/ui/styleTools/buttonStyler.js

* very small screens are now supported.
* improved support for small screens (wrap header and widgets in filter modal)
Previews:
(Modals are scrollable)
Closes #141

feat(front): basic support for extra-small screens

---

web/src/constants/index.js
web/src/store/ResultStore.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/FilterModal/FilterModal.scss
web/src/ui/components/Filters/Filters.js
web/src/ui/pages/Home/Home.js

- add artifact kinds
- update artifact_kinds state from url bar
- request multiple artifact kinds from ui modal
- show all artifact kind filters in header
- all artifact kinds selected if user tries to unselect all (not great UX, will fix when more filters are implemented)
closes #75

feat(front): modify and display artifact kind filters

---

web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/Header/Header.js

feat(web): format card titles with PR links

---

web/src/store/ThemeStore.js
web/src/ui/components/FilterModal/FilterModal.scss
web/src/ui/components/ThemeToggler.js

fix(front): fix unwanted theme change on opening filter settings modal 

---

web/src/ui/components/Header/Header.js

Clicking top-left logo will return search parameters to default and trigger new fetch from API.

feat(web): return home on clicking logo

---

web/src/ui/components/Filters/Filters.js
web/src/ui/components/Filters/Filters.scss
web/src/ui/components/Header/Header.js
web/src/ui/pages/Home/Home.js

feat(front): clicking a filter widget in header opens filter modal

---

web/src/ui/components/Build/ArtifactCard.js
web/src/ui/components/Build/BuildAndMergeRequest.js

(This branch is poorly named.)
Closes #220

fix(front): show build ID rather than mr ID in artifact title

---

web/src/assets/main.scss
web/src/ui/components/Build/Build.scss
web/src/ui/components/Build/BuildContainer.js

feat(front): make build blocks more compact

---

web/package.json
web/src/ui/components/Build/Build.scss
web/src/ui/components/Build/BuildAndMergeRequest.js

Splits build messages along newline character.

feat(web): add linebreaks to build messages

---

web/src/App.js
web/src/ui/components/Header/Header.js
web/src/ui/pages/Error404.js
web/src/ui/pages/Home/Home.js

feat(web): redirect to /404

---

web/.eslintrc.json
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/FilterModal/FilterModal.scss

- re-add rules of hooks to eslint
- lint: remove hook within callback
- remove toggler for filter type
- remove not-allowed cursor on filters that cannot be unselected
Closes #236 #237 #221

fix(front): enable all filter interactivity in modal

---

web/src/api/dataTransforms.js
web/src/assets/main.scss
web/src/constants/index.js
web/src/ui/Tag/Tag.js
web/src/ui/components/AnchorLink.js
web/src/ui/components/AnchorLink.scss
web/src/ui/components/Build/ArtifactActionButton.js
web/src/ui/components/Build/ArtifactCard.js
web/src/ui/components/Build/Build.scss
web/src/ui/components/Build/BuildAndMergeRequest.js
web/src/ui/components/Build/BuildContainer.js
web/src/ui/components/Build/CardHeader.js
web/src/ui/styleTools/brandIcons.js
web/src/ui/styleTools/buttonStyler.js

feat(front): add state tags to collapsed build blocks
Additionally:
- factor out some components
- remove some unused css
- UI tweaks for small mobile
Closes #171

feat(front): add state tags to collapsed build blocks

---

web/src/ui/components/AnchorLink/AnchorLink.js
web/src/ui/components/AnchorLink/AnchorLink.scss
web/src/ui/components/Build/ArtifactCard.js
web/src/ui/components/Build/BuildAndMergeRequest.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/FilterModal/FilterModal.scss

- minor refactor
- bugfix: build driver selection on project filter selection

refactor(front): minor refactor, plus bugfix for gombile filter selector

---

web/package-lock.json
web/package.json
web/src/ui/components/AnchorLink/AnchorLink.js
web/src/ui/components/AnchorLink/AnchorLink.module.scss
web/webpack.config.common.js
web/webpack.config.dev.js
web/webpack.config.prod.js

- enable CSS and SCSS modules
- AnchorLink cleanup to test CSS modules are working
- add common webpack config

build(front): use css modules and some webpack cleanup

---

go/pkg/yolosvc/api_buildlist.go

fix: support artifact_kinds and build_id filters together

---

web/.eslintrc.json
web/package.json
web/src/api/dataTransforms.js
web/src/store/ResultStore.js
web/src/ui/components/AnchorLink/AnchorLink.js
web/src/ui/components/Build/ArtifactCard.js
web/src/ui/components/Build/BuildAndMergeRequest.js
web/src/ui/components/Build/BuildContainer.js
web/src/ui/components/Build/CardHeader.js
web/src/ui/components/BuildList.js
web/src/ui/components/BuildListContainer.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/pages/Home/Home.js
web/src/util/getters.js

- move usememo->regular function call inside component
- remove shadow declarations
- remove unused imports and vars
- add implemented prop to artifact tag (to be able to remove comment)
- add getter utility functions
- simplify (and bugfix) collapse condition

refactor(front): simplify some code in ./web

---

web/.eslintrc.json
web/src/constants/index.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/Filters/Filters.js
web/src/ui/components/Filters/Filters.scss

- adds build driver option to filter modal
- adds build driver filters to header (not beautiful)
Closes #219

feat(front): add build driver filter to filterUI

---

web/src/api/dataGetters.js
web/src/api/dataTransforms.js
web/src/ui/components/Build/BuildContainer.js
web/src/ui/components/BuildList.js
web/src/ui/components/Divider.js
web/src/ui/components/Divider.module.scss
web/src/util/date.js

Light mode:
Dark mode:
Closes #209

feat(web): add build feed date divider

---

web/src/ui/components/Build/BuildAndMrContainer.js
web/src/ui/components/Build/BuildContainer.js

Also have a toggler button to show/hide artifacts for any build in a grouped list.
Relates to #261 
Closes #262 
Closes #264

feat(front): show artifacts if 1st or build branch is master

---

web/.eslintrc.json
web/package-lock.json
web/package.json
web/src/assets/main.scss
web/src/ui/components/Build/ArtifactActionButton.js
web/src/ui/components/Build/ArtifactRow.js
web/src/ui/components/Build/Build.scss
web/src/ui/components/MessageModal/MessageModal.js
web/src/ui/components/ProtocolDisclaimer.js
web/src/ui/components/QRCodeModal.js
web/src/ui/pages/Home/Home.js
web/src/ui/styleTools/buttonStyler.js

feat(web): generate QR code for direct install

---

web/src/ui/components/Build/BuildAndMrContainer.js

Re-add check that build.has_artifacts is an array

fix(front): buildlist crashing when no artifacts

---

web/src/api/mock.js
web/src/store/ResultStore.js
web/src/ui/components/BuildListContainer.js
web/src/ui/components/Filters/Filters.js
web/src/ui/components/Header/Header.js
web/src/ui/components/Spinner.js
web/src/ui/components/Spinner.module.scss
web/src/ui/pages/Home/Home.js

Adds a button to toggle auto-reload functionality (every 10 seconds).
The feature is disabled by default, due to annoying flash of blank page during render of new builds. (See #278 )
- add auto-refresh functionality
- add auto-refresh button to header
- add spinner and dimmer on load
Closes #159

feat(front): Add auto-refresh feature to UI

---

web/src/ui/components/Author/Author.module.scss
web/src/ui/components/Build/BuildBlockHeader.js

fix(front): chevron and author overlap on small screens

---

web/src/constants/index.js
web/src/store/ResultStore.js
web/src/ui/pages/Home/Home.js
web/src/util/browser.js

feat(front): detect and set init artifact kind filters per useragent

---

web/src/App.js
web/src/assets/_variables.scss
web/src/assets/main.scss
web/src/ui/components/ThemeToggler.js

fix(front): invalid destructuring when setting theme
add debounce mimic function to theme toggler

fix(front): set initial theme

---

web/src/ui/components/Build/BuildContainer.js

fix(front): fix hiding latest build when showing all builds

---

go.mod
go.sum
go/pkg/yolosvc/api_plist.go
go/pkg/yolosvc/driver_pkgman.go

fix: various fixes for last PR (extract plist info from artifact)

---

web/package-lock.json
web/package.json
web/src/api/mock.js
web/src/index.js
web/src/store/ResultStore.js
web/src/ui/components/Build/BuildAndMrContainer.js
web/src/ui/components/Build/BuildBlockHeader.js
web/src/ui/components/Build/BuildContainer.js
web/src/ui/components/BuildList.js
web/src/ui/components/BuildListContainer.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/Filters/Filters.js
web/src/ui/components/Spinner/Spinner.module.scss
web/src/ui/pages/Home/Home.js
web/src/wdyr.js

feat(front): remove flash of blank screen on reload

---

web/src/ui/components/AnchorLink/AnchorLink.js
web/src/ui/components/Build/BuildAndMrContainer.js

fix(front): fix anchor link target and web tooltip

---

web/src/ui/components/Build/BuildBlockHeader.js
web/src/ui/components/Build/BuildContainer.js

feat(front): add project avatar and link to BuildBlock header

---

web/src/ui/pages/Home/Home.js

fix(front): set initial artifact kind filter based on useragent

---

web/src/api/apiResponseTransforms.js

A word
Signed-off-by: Elizabeth Kelen <erskelen@gmail.com>

fix(front): master branch filter readd

---

web/src/ui/components/BuildList.js

builds ---> build, hide latest from main feed
Closes #328

feat(front): tweak latest merge on master section

---

web/src/ui/components/AnchorLink/AnchorLink.js
web/src/ui/components/AnchorLink/AnchorLink.module.scss
web/src/ui/components/Build/ArtifactRow.js
web/src/ui/components/Build/BuildAndMrContainer.js

feat(front): add anchor links for artifacts

---

go.mod
go/.golangci.yml
go/Makefile
go/gen.sum
go/pkg/yolopb/types.go
go/pkg/yolopb/types_test.go
go/pkg/yolosvc/api_buildlist.go
go/pkg/yolosvc/api_plist.go

feat: filter-out signed-off-by in messages

---

web/src/App.js
web/src/hooks/useRecursiveTimeout.js
web/src/store/GlobalStore.js
web/src/ui/components/Build/BuildContainer.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/Filters/Filters.js
web/src/ui/components/Header/Header.js
web/src/ui/pages/Home/Home.js

rename ResultStore -> GlobalStore
remove current autorefresh
add recursive timout hook
remove stuff from recursivetimeout
rename ResultContext -> GlobalContext
Related to #348 (splitting out the hook and using setTimeout instead of setInterval seems to have made some improvement)

refactor(front): rename global store, split out autorefresh hook

---

web/.eslintrc.json
web/src/api/index.js
web/src/api/requests.js
web/src/constants/actions.js
web/src/store/GlobalStore.js
web/src/store/globalStoreHelpers.js
web/src/ui/components/ApiKeyPrompt.js
web/src/ui/components/BuildList.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/Filters/Filters.js
web/src/ui/components/Header/Header.js
web/src/ui/pages/Home/Home.js

- Starts cleaning up Home component
- Starts adding actions other than "update global state" to reducer
WIP as I need to test this seriously and then clean up the action names in store and some other small things.
Relates to #306

refactor(front): reduce useEffect abuse in Home component

---

web/src/ui/components/Build/BuildBlockTitle.js

feat(front): add merge request messge to block subtitle on master

---

web/.eslintrc.json
web/src/api/requests.js
web/src/hooks/useRedirectOnEmptyQuery.js
web/src/hooks/useRequestOnQueryChange.js
web/src/hooks/useSetFiltersOnQueryChange.js
web/src/store/GlobalStore.js
web/src/ui/components/Build/BuildBlockHeader.js
web/src/ui/components/Build/BuildBlockTitle.js
web/src/ui/components/Build/BuildContainer.js
web/src/ui/components/BuildList.js
web/src/ui/components/Divider/Divider.js
web/src/ui/components/Divider/Divider.module.scss
web/src/ui/components/Filters/Filters.js
web/src/ui/pages/Home/Home.js
web/src/util/misc.js

Removes 'latest build on master' divider and replaces it with a ⭐ !
Re-adds date dividers in horizontal rule.
Related to #345

feat(front): feed dividers and latest master star

---

web/src/hooks/queryHooks.js
web/src/store/GlobalStore.js
web/src/ui/components/ApiKeyPrompt.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/Filters/Filters.js

Keep URL bar search query if user has 401 from server.
Closes #357

fix(fron): fix lost query string in URL bar on 401 error from server

---

web/src/ui/components/Build/BuildBlockHeader.js
web/src/ui/components/BuildList.js

feat(web): hide full feed by default

---

web/.eslintrc.json
web/src/ui/components/Build/ArtifactRow.js
web/src/ui/components/Build/Build.module.scss
web/src/ui/components/BuildList.js
web/src/ui/styleTools/themes.js

Add new DL button and styles to artifact sections.
**also**
- improve primary button text color
- soften dividers in build blocks

feat(front): improve artifact download button

---

web/src/ui/components/Build/ArtifactRow.js
web/src/ui/components/BuildList.js
web/src/ui/components/Filters/Filters.js

- Hide '0' in header when no options selected for a filter
- Fix anchor link copying `artifact_kinds=undefined` for unknown artifact platform

fix(front): minor ui improvements

---

deployments/yolo.berty.io/docker-compose.yml

Signed-off-by: Guilhem Fanton <guilhem.fanton@gmail.com>

feat(deployment): add traefik labels to compose

---

go/pkg/yolosvc/driver_github.go
go/pkg/yolosvc/server.go

this routine will run every 10 github runs to check if some orphan builds can be linked to the matching PR

feat: add a new routine that tries to fix orphans

---

web/.babelrc
web/package-lock.json
web/package.json
web/src/ui/components/BuildList.js
web/src/util/misc.js

- scroll-to behavior when showing/hiding feed
- 'scroll to top' button when feed has at least 5 merge requests visible

feat(js): scroll-to behavior when showing/hiding feed

---

web/src/api/index.js
web/src/hooks/queryHooks.js
web/src/store/GlobalStore.js
web/src/store/globalStoreHelpers.js
web/src/ui/components/BuildList.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/Filters/Filters.js
web/src/ui/components/MessageModal/MessageModal.scss
web/src/ui/components/ProtocolDisclaimer.js
web/src/ui/components/PullToRefresh.js
web/src/ui/pages/Home/Home.js
web/src/ui/pages/Home/Home.module.scss

Swipe down on iOS/Android to refresh. The animation isn't instantaneous but the functionality seems worth keeping.
Also hides empty footer on mobile (it's ugly on mobile browsers that allow drag at bottom of view).

fix: pull to refresh

---

web/src/ui/components/BuildList.js

feat(front): easier-to-press feed display toggler

---

web/src/ui/components/Build/BuildContainer.js

Signed-off-by: Elizabeth Kelen <erskelen@gmail.com>

fix(ui): collapsed block download btn click event propagates

---

web/src/ui/components/Build/BuildContainer.js
web/src/ui/components/BuildList.js

Signed-off-by: clegirar <clemntgirard@gmail.com>

fix: last build default collapse as true

---

go/pkg/yolostore/store.go

feat: support repo project format {orga}/{repo}
