web/src/ui/components/BuildCard/ArtifactCard.js
web/src/ui/components/BuildCard/BuildCard.js

Related to #71 
Card title:
1. MR title if available
2. `Pull: <MR short ID>`
3. `Build: <build short ID>`
4. Blank
Note: Option of title `Master` is removed, so a merge on Master with no MR will have title `Build: <build short ID>`

Add MR Title with PR id and Build ID fallbacks to card title

---

web/src/api/dataTransforms.js
web/src/ui/components/BuildList.js

- refactor: items --> builds
- Add collapse condition function
- Collapse cards if master branch is present in query results
**Asking for review; 2 questions:**
1. Is this really the intended behaviour (do we want to hide collapse ALL build details if ANY master branch build is present, or only collapse branch details if it shares a build short ID with a Master build short ID)?
2. Bintray builds and others with no `build.branch` or `build.has_mergerequest.branch` - collapse or no?
Closes #168

Feat(web): Collapse cards if any branch in results is master

---

web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/BuildCard/BuildCard.scss

Small screens:
Large screens:
Also changes `Build <BuildId>` to `Master <BuildId>` if there is a build branch called Master (these do not have MR short Id's as far as I can tell.)
Closes #173

Fix: Keep MR message as subtitle in buildcards

---

web/package.json
web/src/api/mock.js

Uses axios to fetch a defined static file served over HTTP, as I often want to test the UI with custom cases.
Setting `MOCK_DATA_FILE_ENDPOINT` will allow axios to read this file if `npm run start-ui-test` is run from ./web directory.

test(front): update fetch stub

---

web/package-lock.json
web/package.json
web/src/constants/index.js
web/src/store/ResultStore.js
web/src/ui/components/AnchorLink.js
web/src/ui/components/BuildCard/ArtifactCard.js
web/src/ui/components/BuildCard/BuildCard.js
web/src/ui/components/BuildCard/BuildCard.scss
web/src/ui/components/BuildList.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/ShowFiltersButton.js
web/src/ui/pages/Home/Home.js

Normally there is now an anchor link available next to each build card header and individual artifacts; copies to clipboard on click.
Closes #180

feat(front): add anchor links to builds and artifacts

---

web/src/ui/components/MessageModal/MessageModal.js
web/src/ui/components/MessageModal/MessageModal.scss

Add shadow to button (same style as green download button in Artifact list), darken background on hover
(Preview on hover:)
Closes #203

fix(front): make protocol warning button look interactive

---

web/src/constants/index.js
web/src/store/ResultStore.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/FilterModal/FilterModal.scss
web/src/ui/components/Filters/Filters.js
web/src/ui/pages/Home/Home.js

TODO:
* allow filtering by project OR artifact kinds from filter modal
* add gomobile-ipfs-demo (is there a shorter name for this?) to UI
* filter by project gomobile-ipfs-demo triggers query `?artifact_kinds=2&artifact_kinds=1&build_driver=3`
* filter by project chat triggers query `?artifact_kinds=1&build_driver=1`
Style tweaks:
* add style for disabled filters in modal
Blocks #202 
Closes #201

feat(front): allow filtering from ui by project

---

web/.eslintrc.json
web/src/ui/components/AnchorLink.js
web/src/ui/components/Build/ArtifactCard.js
web/src/ui/components/Build/Build.scss
web/src/ui/components/Build/BuildAndMergeRequest.js

- add anchor link to artifacts
- add anchor link to builds (commented out until API is working)
Unlike old version (#205 ) this one simply copies the URL (not target link) of yolo URL w/ search params corresponding to artifact/link.

feat(front): add sharable links to builds and artifacts in feed

---

web/src/store/ResultStore.js
web/src/ui/components/BuildList.js
web/src/ui/components/BuildListContainer.js
web/src/ui/pages/Home/Home.js

- Make frontend calculation of build groups happen in memoizing callback (in order to reduce prop drilling and unnecessary global state modification)
- Split BuildList --> BuildListContainer + BuildList
- Style Loading and NoBuilds as sub-components
Blocks #209

refactor(front): memoize build grouping and split out build components

---

web/src/api/dataGetters.js
web/src/api/dataTransforms.js
web/src/ui/components/Build/BuildAndMrContainer.js
web/src/ui/components/Build/BuildBlockHeader.js
web/src/ui/components/Build/BuildContainer.js
web/src/ui/components/BuildList.js
web/src/util/getters.js

- show X Builds Running on collapsed build block (if it is a block grouped by MR, with N builds > 1 and at least one build in grouped block having build.state === Running)
Relates to #144

feat(front): show running build count in collapsed blocks

---

web/src/ui/components/Build/ArtifactRow.js
web/src/ui/components/Build/BuildBlockHeader.js
web/src/ui/components/Build/BuildContainer.js
web/src/ui/styleTools/themes.js

- use GitHub colors and pull request icon for builds with GH MR attached
- fix up GH colors for our dark mode
---
Also:
- remove state tag from artifact row

feat(front): build block header icons correspond to MR status

---

web/src/constants/index.js
web/src/ui/pages/Home/Home.js

For performance reasons, limit API request to 25 builds if user has unselected all filters in UI.

feat(front): request 25 builds if no UI filters are in place

---

web/src/api/cookies.js

there are no security/privacy concerns here, and this is typically the kind of app you don't open for weeks/months

chore: increase default cookie expiration

---

web/src/api/apiResponseTransforms.js
web/src/ui/components/BuildList.js

Grouping data by MR and date was previously occurring on every global state change.

fix(front): call buildlist formatters only on api data receipt

---

web/src/ui/components/Author/Author.js
web/src/ui/components/Build/ArtifactRow.js
web/src/ui/components/Build/Build.scss
web/src/ui/components/Build/BuildAndMrContainer.js
web/src/ui/components/Build/BuildAndMrContainerWidgets.js
web/src/ui/components/Build/BuildBlockHeader.js
web/src/ui/components/Build/BuildContainer.js
web/src/ui/components/Build/BuildMessage.js
web/src/ui/components/ConditionallyWrappedComponent.js
web/src/ui/components/ShowingOlderBuildsTag.js
web/src/ui/styleTools/buttonStyler.js
web/src/ui/styleTools/themes.js

- Splits out most nested components inside `src/ui/components/Build` (everything related to API response with build data)
- Renames some variables and files for clarity (still some work left to do on this)
- Removes some unused abstractions and styling tools
Unrelated:
- Theme fix: Add primary button color

refactor(front): split out build-block related subcomponents

---

go.mod
go.sum
go/pkg/yolosvc/api_artifactgetfile.go
go/pkg/yolosvc/api_download.go
go/pkg/yolosvc/server.go
go/pkg/yolosvc/service.go
go/pkg/yolosvc/util.go

moul@fwrz:~ $ http --auth :uns3cur3 http://localhost:8067/api/artifact-get-file/buildkite_4a7ff9305bb3cb504d396edbf07c27bb/Payload/Berty%20Yolo.app/Info.plist
HTTP/1.1 200 OK
Content-Type: application/x-plist
Date: Mon, 08 Jun 2020 21:24:34 GMT
Transfer-Encoding: chunked
Vary: Origin
+-----------------------------------------+
| NOTE: binary data not shown in terminal |
+-----------------------------------------+
moul@fwrz:~ $

feat: add an helper to extract a file from an artifact

---

web/src/api/apiResponseTransforms.js
web/src/ui/components/BuildList.js
web/src/util/date.js

- If there are > 1 builds (grouped by MR, if one exists) for a project/projects, and the grouped build is on branch master, they are shown at the top of feed
- There can be > 1 build in this top section if there are multiple projects in the results list
- Any builds in this section will be shown in the "All builds by date" section too, but collapsed by default
Relates to #328 (still need to treat running builds)

feat(front): show latest master builds at top of feed

---

web/src/ui/components/Build/ArtifactRow.js
web/src/ui/components/Build/BuildBlockHeader.js
web/src/ui/components/Build/BuildContainer.js

Previously only the header of a collapsed build block in feed could handle click to expand/collapse, now the entire collapsed block can be clicked to expand. (If block is expanded, only the header or its chevron can be clicked to collapse it.)
Related to #365

fix(front): clicking entire collapsed build block now toggles collapsed state

---

web/src/store/ThemeStore.js

I've spent 1h30 implementing the same for filters without realizing yolo already somehow remember your builds (I have no idea where it's done but on the https://yolo.berty.io/ build filters are remembered cross reload).

feat: Store Theme in localStorage.

---

web/src/constants/index.js
web/src/hooks/queryHooks.js
web/src/store/GlobalStore.js
web/src/store/ThemeStore.js
web/src/store/globalStoreHelpers.js
web/src/ui/components/BuildList.js
web/src/ui/components/FilterModal/FilterModal.js
web/src/ui/components/FilterModal/FilterModalWidgets.js

On navigation to home with no query params (assuming you have nothing in localStorage):
- Removes default build driver param
- Adds plaintext messenger URL as default `project_id` query param
- As before: Keeps default behavior of using useragent to detect artifact kind if on mobile; otherwise defaults to IPA only
- Also removes association everywhere between filters on build drivers<->project (selecting a project in UI will no longer append specific build drivers to query, as before)
nb:
- There are some pre-existing strange behaviors with localStorage vs. nav bar query params not addressed in this MR.
- Manually adding `project_id=__BERTY URL__` in nav bar will not update UI Filters (i.e. add the berdy logo in header – you must select Messenger via filters modal for that)
----------- …

chore: update default options

---

go/cmd/yolo/main.go
go/cmd/yolo/server.go
go/cmd/yolo/store.go
go/pkg/yolosvc/server.go

relate to #456
Can't use exactly the same code style cause berty/yolo is using ffcli/v2 instead of ffcli/v3 for berty/berty

feat: modify flags define
